### ISSUE TITLE
Discord Integration?

### ISSUE THREAD

**Issue by lemtzas** [josefnpat/pico8collab16#22]
https://github.com/Falconerd/discord-bot-github

Quick instructions: ([detailed instructions here](https://github.com/Falconerd/discord-bot-github#setup))

* Add a webhook to your repository pointing to `https://discordbotgithub.herokuapp.com`. Select any events you would like to listen for.
  * Repo -> Settings -> Webhooks & Services -> Add Webhook -> `https://discordbotgithub.herokuapp.com`
* Authorize the bot on your server by clicking [this link.](https://discordapp.com/oauth2/authorize?&client_id=193000403632128013&scope=bot&permissions=3072)
* On server: `!dbg add josefnpat/pico8collab16`

**Comment by josefnpat** [comment]
Tested and done
